### ISSUE TITLE
Move CLI to tydoc package and extractor to @tydoc/extractor package

### ISSUE THREAD

**Issue by jasonkuhrt** [tydoc/tydoc#56]
https://github.com/tydoc/tydoc

**Comment by jasonkuhrt** [comment]
@williamluke4 why closed?

**Comment by jasonkuhrt** [comment]
This issue was created before the monorepo switch. Retitling the issue for clarity now.

**Comment by williamluke4** [comment]
> @williamluke4 why closed?
No idea :-/

**Comment by jasonkuhrt** [comment]
closed by fbaef25
