### ISSUE TITLE
Workflow TS 4.1 quirk

### ISSUE THREAD

**Issue by jasonkuhrt** [tydoc/tydoc#75]
This is a temp issue until TS 4.1 is the default TS version with VSCode.

When opening VSCode from within a package the default version of TS used is 4.0. 

E.g.:

```
cd packages/extactor && code .
```

Then, VSCode gives an error for the `tsconfig.json` saying that the `baseURL option must be passed because paths is being used`.

This is because the VSCode is using TS 4.0 because settings in monorepo root aren't picked up when VSCode uses a package dir as the workspace root.

Some solutions are:

1. Don't open VSCode to package directories Until VSCode ships with TS 4.1
2. Put a .vscode/settings.json into each package directory

I think Option 2 is the best in terms of making the project more seamless to work on.

**Comment by schickling** [comment]
Happy with either. I personally only open one VSC per monorepo.
